jjtree with relevant information at each node

diff --git a/assignment2/s b/assignment2/s
--- a/assignment2/s
+++ b/assignment2/s
@@ -2,12 +2,14 @@
 
 # https://github.com/javacc/javacc/archive/javacc-7.0.11.tar.gz
 
-rm -rf lp
-mkdir lp
+DIR_NAME=lp
+
+# rm -rf $DIR_NAME
+# mkdir $DIR_NAME
 
 java -cp javacc-javacc-7.0.11/bootstrap/javacc.jar \
       jjtree \
-      -OUTPUT_DIRECTORY=lp \
+      -OUTPUT_DIRECTORY=$DIR_NAME \
       Language.jjt
 
 if [ $? -ne 0 ]; then
@@ -17,15 +19,23 @@ fi
 
 java -cp javacc-javacc-7.0.11/bootstrap/javacc.jar \
       org.javacc.parser.Main \
-      -OUTPUT_DIRECTORY=lp \
-      lp/Language.jj
+      -OUTPUT_DIRECTORY=$DIR_NAME \
+      $DIR_NAME/Language.jj
 
 if [ $? -ne 0 ]; then
         echo "Did not successfully run javacc"
-        exit 1
+        exit 2
 fi
 
-( cd lp
+cp *Visitor.java $DIR_NAME/
+
+( cd $DIR_NAME
   javac *.java
-  java -cp . Lexer $1
+  java -cp . Lexer "../${1}"
+  if [ $? -ne 0 ]; then
+        echo "Runtime Error"
+        exit 3
+  fi
 )
+
+echo "SUCCESS" > OUTPUT
