finished coverage listener

diff --git a/assignment3/s b/assignment3/s
--- a/assignment3/s
+++ b/assignment3/s
@@ -1,15 +1,36 @@
 #!/bin/bash
 
 if [ $# -eq 0 ]; then
-    echo "No program input supplied"
+    echo "No input program supplied"
     exit 1
 else
-    PROGRAM=$1
-    javac ${PROGRAM}
+    # build jpf-core
+    if [ ! -d jpf-core ]; then
+        echo "Downloading jpf-core"
+        git clone https://github.com/javapathfinder/jpf-core
+    fi
     ( cd jpf-core
-        gradle buildJars
-        bin/jpf +classpath=.. ${PROGRAM%%.*}
+        sed -i 's/public void setJavaObjectInputStreamReadString.*/public void setJavaObjectInputStreamReadString() {/g' src/classes/sun/misc/SharedSecrets.java
+        gradle buildJars -x test
     )
+
+    # compile listeners
+    javac -d build/ -classpath jpf-core/build/jpf.jar src/*.java
+    if [ $? -ne 0 ]; then
+        echo "ERROR: compilation of listeners failed"
+        exit 1
+    fi
+
+    # compile input program
+    PROGRAM=$1
+    javac -d build/ ${PROGRAM}
+    if [ $? -ne 0 ]; then
+        echo "ERROR: compilation of input program failed"
+        exit 1
+    fi
+
+    jpf-core/bin/jpf +native_classpath=build/ +classpath=build/ +listener=CoverageListener ${PROGRAM%%.*}
 fi
+
 
 
